name: 'smart_retail'
version: '1.0.0'
config-version: 2

profile: 'smart_retail'

model-paths: ["models"]
macro-paths: ["macros"]
test-paths: ["tests"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  smart_retail:
    gold:
      +materialized: table
